site_name: Witcan
site_description: .net,java,php,python,docker,web
site_author: Witcan
site_url: https://witcan.github.io
# site_favicon: favicon.ico
# copyright: Witcan
repo_name: 'witcan.github.io'
repo_url: 'https://github.com/witcan/witcan.github.io'

theme:
    name: material
    highlightjs: true
    favicon: favicon.ico
    language: 'zh'
    feature:
        tabs: false
    hljs_languages:
        - yaml
        - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

nav:
  - 介绍: index.md
  - 技术博文:
    - Ruby:
        - Docker 容器化部署 ASP.NET Core: net/c_sqlserver_nginx.md
        - 让你的ASP.NET Core应用程序更安全: net/c_core_safety.md
        - ASP.NET Core开发者指南: net/c_core_study_route.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
