site_name: 小艾的杂货铺
site_description: .net,java,php,python,docker,web
site_author: 艾宇航
site_url: https://witcan.github.io
# site_favicon: assets/images/logo.png
repo_name: 'witcan.github.io'
repo_url: 'https://github.com/witcan/witcan.github.io'

theme:
    name: material
    highlightjs: true
    # logo: assets/images/favicon.png
    # favicon: assets/images/logo.png
    language: 'zh'
    feature:
        tabs: false
    hljs_languages:
        - yaml
        - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

nav:
  - 介绍: index.md
  - 情感:
    - 工作心得: emotion/workheart.md
  - 数据库:
    - 表管理: mysql/20220622.md
    - 数据管理: mysql/20220623.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
extra_css:
  - 'assets/stylesheets/extra.css'
# extra:
#     version: 1.0
#     search:
#         language: 'zh,en,ja'
#         tokenizer: '[\ s \-\ .. +'
#     palette:
#         primary: 'Blue Grey'
#         accent: 'Pink'
#     social:
#     - type: 'github'
#       link: 'https://github.com/burningmyself'
#     - type: 'google'
#       link: 'https://gitee.com/burningmyself'